In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('CHURN.csv')
df.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  7043 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          7043 non-null   object 
 16  PaperlessBilling  7043 non-null   object 


Nice....no nulls

In [4]:
df['Churn'] = df['Churn'].replace(to_replace=['No','Yes'], value=[0,1])

C:\Users\angst\AppData\Local\Temp\ipykernel_57736\3062082239.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Churn'] = df['Churn'].replace(to_replace=['No','Yes'], value=[0,1])


Gross...deprecation warnings

In [6]:
X=df.iloc[:,1:-1]
y=df.iloc[:,-1]

In [7]:
X=pd.get_dummies(X)

In [8]:
from sklearn.model_selection import cross_val_score

In [11]:
def clf_model(model):
    clf=model
    scores = cross_val_score(clf, X, y)
    print(f'Scores: {scores}')
    print(f'Mean score: {scores.mean()}')
    

In [12]:
from sklearn.naive_bayes import GaussianNB
clf_model(GaussianNB())

Scores: [0.28246984 0.2782115  0.29027679 0.27556818 0.27698864]
Mean score: 0.2807029889025099


In [13]:
from sklearn.neighbors import KNeighborsClassifier
clf_model(KNeighborsClassifier())

C:\Users\angst\anaconda3\Lib\site-packages\joblib\externals\loky\backend\context.py:136: UserWarning: Could not find the number of physical cores for the following reason:
[WinError 2] The system cannot find the file specified
Returning the number of logical cores instead. You can silence this warning by setting LOKY_MAX_CPU_COUNT to the number of cores you want to use.
  warnings.warn(
  File "C:\Users\angst\anaconda3\Lib\site-packages\joblib\externals\loky\backend\context.py", line 257, in _count_physical_cores
    cpu_info = subprocess.run(
               ^^^^^^^^^^^^^^^
  File "C:\Users\angst\anaconda3\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\angst\anaconda3\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\angst\anaconda3\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreatePro

Scores: [0.77288857 0.78779276 0.76011356 0.76349432 0.77627841]
Mean score: 0.772113523453126


In [14]:
from sklearn.tree import DecisionTreeClassifier
clf_model(DecisionTreeClassifier(random_state=0))

Scores: [0.76863023 0.761533   0.75585522 0.76136364 0.76988636]
Mean score: 0.7634536905606814


In [15]:
from sklearn.ensemble import RandomForestClassifier
clf_model(RandomForestClassifier(random_state=0))

Scores: [0.79347055 0.79276082 0.77217885 0.79403409 0.79048295]
Mean score: 0.788585453093748


In [16]:
from sklearn.linear_model import LogisticRegression
clf_model(LogisticRegression(max_iter=1000))

Scores: [0.80340667 0.81476224 0.78992193 0.80823864 0.80255682]
Mean score: 0.8037772598232144


In [17]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.25, random_state=0)

In [19]:
def confusion(model):
    clf=model
    clf.fit(X_train,y_train)
    y_pred = clf.predict(X_test)
    print(confusion_matrix(y_test, y_pred))
    print(classification_report(y_test, y_pred))
    return clf

In [20]:
confusion(LogisticRegression(max_iter=1000))

[[1161  137]
 [ 221  242]]
              precision    recall  f1-score   support

           0       0.84      0.89      0.87      1298
           1       0.64      0.52      0.57       463

    accuracy                           0.80      1761
   macro avg       0.74      0.71      0.72      1761
weighted avg       0.79      0.80      0.79      1761



LogisticRegression(max_iter=1000)

In [22]:
confusion(RandomForestClassifier(random_state=0))

[[1166  132]
 [ 267  196]]
              precision    recall  f1-score   support

           0       0.81      0.90      0.85      1298
           1       0.60      0.42      0.50       463

    accuracy                           0.77      1761
   macro avg       0.71      0.66      0.67      1761
weighted avg       0.76      0.77      0.76      1761



RandomForestClassifier(random_state=0)

In [23]:
confusion(KNeighborsClassifier())

[[1124  174]
 [ 219  244]]
              precision    recall  f1-score   support

           0       0.84      0.87      0.85      1298
           1       0.58      0.53      0.55       463

    accuracy                           0.78      1761
   macro avg       0.71      0.70      0.70      1761
weighted avg       0.77      0.78      0.77      1761



KNeighborsClassifier()

In [24]:
from sklearn.ensemble import AdaBoostClassifier
clf_model(AdaBoostClassifier())

C:\Users\angst\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
C:\Users\angst\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
C:\Users\angst\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
C:\Users\angst\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
C:\Users\ang

Scores: [0.81263307 0.80411639 0.78992193 0.80184659 0.8046875 ]
Mean score: 0.8026410978127622


In [25]:
confusion(AdaBoostClassifier())

C:\Users\angst\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


[[1149  149]
 [ 212  251]]
              precision    recall  f1-score   support

           0       0.84      0.89      0.86      1298
           1       0.63      0.54      0.58       463

    accuracy                           0.80      1761
   macro avg       0.74      0.71      0.72      1761
weighted avg       0.79      0.80      0.79      1761



AdaBoostClassifier()